name: Sync Github Repositories To Gitee
on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        uses: sunn4room/sync2gitee@main
        with:
          repositories: |
            junegunn/fzf.vim
            folke/lazy.nvim
          gitee-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}
          gitee-token: ${{ secrets.GITEE_TOKEN }}
          gitee-org: sunn4mirror
