name: Sync Github Repositories To Gitee
on:
  push:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: sync repos
        uses: ./
        with:
          repositories: |
            ohmyzsh/ohmyzsh
            zsh-users/zsh-completions
            zsh-users/zsh-syntax-highlighting
            zsh-users/zsh-autosuggestions
            morhetz/gruvbox
            vim-airline/vim-airline
            tpope/vim-commentary
            easymotion/vim-easymotion
            junegunn/fzf.vim
            iamcco/markdown-preview.nvim
            neoclide/coc.nvim@release
            Ulauncher/Ulauncher@v6
            vuejs/core->vue3
            plantuml/plantuml
          gitee-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}
          gitee-token: ${{ secrets.GITEE_TOKEN }}
          gitee-org: sunn4mirror
